---
# tasks file for install_FTP
- name: install ftp
  yum:
    name: vsftpd
    state: installed
  notify: 
    - start_FTP    
- name: open port
  firewalld:
    port: 1024/tcp
    permanent: yes
    state: enabled
- name: use template
  template:
    src: my.j2
    dest: /etc/vsftpd/vsftpd.conf
  notify: 
    - SELinux 
    - restart_FTP
